# name: Terraform Azure Landing Zone

# on:
#   push:
#     branches:
#       - main
#       - feature/copy1


# permissions:
#   contents: read

# env:
#   TF_WORKING_DIR: ./azure_landing_zone/environment/dev

# jobs:

#   # ==================================================
#   # TERRAFORM PLAN
#   # ==================================================

#   terraform-plan:
#     name: Terraform Init Validate Plan
#     runs-on: ubuntu-latest

#     steps:

#       # Checkout
#       - name: Checkout Repository
#         uses: actions/checkout@v4

#       # Azure Login
#       - name: Azure Login
#         uses: azure/login@v2
#         with:
#           creds: |
#             {
#               "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
#               "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
#               "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
#               "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
#             }

#       # Terraform
#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v3

#       # Init
#       - name: Terraform Init
#         working-directory: ${{ env.TF_WORKING_DIR }}
#         run: terraform init

#       # Format
#       - name: Terraform Format Check
#         working-directory: ${{ env.TF_WORKING_DIR }}
#         run: terraform fmt -check -recursive

#       # Validate
#       - name: Terraform Validate
#         working-directory: ${{ env.TF_WORKING_DIR }}
#         run: terraform validate

#       # Plan
#       - name: Terraform Plan
#         working-directory: ${{ env.TF_WORKING_DIR }}
#         run: terraform plan -out=tfplan

#       # Upload Plan
#       - name: Upload Terraform Plan
#         uses: actions/upload-artifact@v4
#         with:
#           name: terraform-plan
#           path: ${{ env.TF_WORKING_DIR }}/tfplan


#   # ==================================================
#   # PRODUCTION APPLY
#   # ==================================================

#   terraform-apply:
#     name: Production Terraform Apply
#     needs: terraform-plan

#     # ================================================
#     # IMPORTANT
#     # Production environment has required reviewers
#     # ================================================
#     environment:
#       name: Production

#     # Only Apply from main branch
#     if: github.ref == 'refs/heads/main' && github.event_name == 'push'

#     runs-on: ubuntu-latest

#     steps:

#       # Checkout
#       - name: Checkout Repository
#         uses: actions/checkout@v4

#       # Azure Login
#       - name: Azure Login
#         uses: azure/login@v2
#         with:
#           creds: |
#             {
#               "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
#               "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
#               "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
#               "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
#             }

#       # Terraform
#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v3

#       # Init
#       - name: Terraform Init
#         working-directory: ${{ env.TF_WORKING_DIR }}
#         run: terraform init

#       # Download Plan
#       - name: Download Terraform Plan
#         uses: actions/download-artifact@v4
#         with:
#           name: terraform-plan
#           path: ${{ env.TF_WORKING_DIR }}

#       # Apply
#       - name: Terraform Apply
#         working-directory: ${{ env.TF_WORKING_DIR }}
#         run: terraform apply -auto-approve tfplan







name: Terraform Azure Landing Zone

on:
  push:
    branches:
      - main
      - feature/copy1

permissions:
  contents: read

env:
  TF_WORKING_DIR: ./azure_landing_zone/environment/dev

jobs:

  # ==================================================
  # TERRAFORM PLAN
  # ==================================================

  terraform-plan:
    name: Terraform Init Validate Plan
    runs-on: self-hosted

    steps:

      # Checkout
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Azure Login
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }

      # Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Terraform Init
      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        shell: powershell
        run: |
          terraform init

      # Terraform Format
      - name: Terraform Format Check
        working-directory: ${{ env.TF_WORKING_DIR }}
        shell: powershell
        run: |
          terraform fmt -check -recursive

      # Terraform Validate
      - name: Terraform Validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        shell: powershell
        run: |
          terraform validate

      # Terraform Plan
      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        shell: powershell
        run: |
          terraform plan -out=tfplan

          Write-Host "===================================="
          Write-Host "Checking Terraform Plan File"
          Write-Host "===================================="

          Get-ChildItem -Path . -Force

          if (!(Test-Path ".\tfplan")) {
              Write-Error "Terraform plan file was not created!"
              exit 1
          }

          Write-Host "Terraform plan file created successfully."
          Get-Item ".\tfplan"

      # Upload Terraform Plan
      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: ${{ env.TF_WORKING_DIR }}/tfplan
          if-no-files-found: error


  # ==================================================
  # PRODUCTION APPLY
  # ==================================================

  terraform-apply:
    name: Production Terraform Apply
    needs: terraform-plan

    # Production Environment
    # Required reviewer approval configured in GitHub
    environment:
      name: Production

    # Apply only when code is pushed to main
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    runs-on: self-hosted

    steps:

      # Checkout
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Azure Login
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }

      # Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Terraform Init
      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        shell: powershell
        run: |
          terraform init

      # Download Terraform Plan
      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: ${{ env.TF_WORKING_DIR }}

      # Verify Terraform Plan
      - name: Verify Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        shell: powershell
        run: |
          Write-Host "===================================="
          Write-Host "Checking Downloaded Terraform Plan"
          Write-Host "===================================="

          Get-ChildItem -Path . -Force

          if (!(Test-Path ".\tfplan")) {
              Write-Error "Terraform plan file was not downloaded!"
              exit 1
          }

          Write-Host "Terraform plan downloaded successfully."
          Get-Item ".\tfplan"

      # Terraform Apply
      - name: Terraform Apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        shell: powershell
        run: |
          terraform apply -auto-approve tfplan